# -*- coding: utf-8 -*-

# JUH QUIZ 1.5 — 18 VÍDEOS
# 6 temas x 3 vídeos por tema x 5 perguntas
#
# Layouts:
# 1 = Eleições / Informativo
# 2 = Casal Flertando
# 3 = Rock in Rio / Festival
# 4 = Semana do Cinema
# 5 = Nossa Um Peão Desse / Country
# 6 = Morango Cravejado
#
# correta:
# 0 = A
# 1 = B
# 2 = C
# 3 = D

VIDEOS = [{'id': 'eleicoes_01',
  'layout': 1,
  'tema': 'ELEIÇÕES 2026',
  'hashtag': '#Eleições2026',
  'gancho': 'Você está por dentro das Eleições 2026?',
  'perguntas': [{'pergunta': 'Em que dia acontece o primeiro turno das Eleições 2026?',
                 'opcoes': ['27 de setembro', '4 de outubro', '11 de outubro', '25 de outubro'],
                 'correta': 1,
                 'explicacao': 'O primeiro turno das Eleições 2026 será realizado em 4 de outubro.'},
                {'pergunta': 'Se houver segundo turno, em que dia ele será realizado?',
                 'opcoes': ['11 de outubro', '18 de outubro', '1º de novembro', '25 de outubro'],
                 'correta': 3,
                 'explicacao': 'O eventual segundo turno está marcado para 25 de outubro.'},
                {'pergunta': 'Qual será o horário de votação nas Eleições 2026?',
                 'opcoes': ['Das 8h às 17h', 'Das 7h às 16h', 'Das 9h às 18h', 'Das 8h às 18h'],
                 'correta': 0,
                 'explicacao': 'A votação ocorrerá das 8h às 17h, pelo horário oficial de Brasília.'},
                {'pergunta': 'Quantos senadores serão escolhidos nas Eleições 2026?',
                 'opcoes': ['27', '81', '54', '108'],
                 'correta': 2,
                 'explicacao': 'Em 2026 serão escolhidos 54 senadores, correspondentes a dois terços do '
                               'Senado.'},
                {'pergunta': 'Qual destes cargos não será escolhido nas Eleições 2026?',
                 'opcoes': ['Governador', 'Prefeito', 'Senador', 'Presidente da República'],
                 'correta': 1,
                 'explicacao': 'Prefeitos são escolhidos nas eleições municipais, e não nas eleições gerais '
                               'de 2026.'}],
  'fechamento': 'Quantas você acertou? Confira sempre as informações oficiais da Justiça Eleitoral.'},
 {'id': 'eleicoes_02',
  'layout': 1,
  'tema': 'ORDEM DE VOTAÇÃO 2026',
  'hashtag': '#Eleições2026',
  'gancho': 'Você sabe a ordem correta de votação na urna?',
  'perguntas': [{'pergunta': 'Qual será a primeira escolha do eleitor na urna em 2026?',
                 'opcoes': ['Presidente', 'Governador', 'Deputado Federal', 'Senador'],
                 'correta': 2,
                 'explicacao': 'A primeira escolha na urna será para deputado federal.'},
                {'pergunta': 'Depois de deputado federal, qual cargo aparece na urna?',
                 'opcoes': ['Deputado Estadual ou Distrital', 'Governador', 'Presidente', 'Senador'],
                 'correta': 0,
                 'explicacao': 'A segunda escolha será para deputado estadual ou distrital.'},
                {'pergunta': 'Quantas escolhas para senador o eleitor fará em 2026?',
                 'opcoes': ['Uma', 'Três', 'Quatro', 'Duas'],
                 'correta': 3,
                 'explicacao': 'Em 2026 o eleitor fará duas escolhas para o Senado.'},
                {'pergunta': 'Qual cargo aparece imediatamente antes de presidente na urna?',
                 'opcoes': ['Senador', 'Governador', 'Deputado Federal', 'Deputado Estadual'],
                 'correta': 1,
                 'explicacao': 'Governador será a penúltima escolha da votação.'},
                {'pergunta': 'Qual será a última escolha na urna eletrônica em 2026?',
                 'opcoes': ['Governador', 'Senador', 'Presidente da República', 'Deputado Federal'],
                 'correta': 2,
                 'explicacao': 'Presidente da República será a última escolha na sequência da urna.'}],
  'fechamento': 'Você lembraria dessa ordem na hora de votar?'},
 {'id': 'eleicoes_03',
  'layout': 1,
  'tema': 'REGRAS DO VOTO 2026',
  'hashtag': '#Eleições2026',
  'gancho': 'Será que você conhece mesmo as regras das Eleições 2026?',
  'perguntas': [{'pergunta': 'Qual é a idade mínima para concorrer ao cargo de deputado federal?',
                 'opcoes': ['21 anos', '18 anos', '30 anos', '35 anos'],
                 'correta': 0,
                 'explicacao': 'A idade mínima para deputado federal é de 21 anos.'},
                {'pergunta': 'Qual é a idade mínima para concorrer ao Senado?',
                 'opcoes': ['30 anos', '35 anos', '40 anos', '21 anos'],
                 'correta': 1,
                 'explicacao': 'A idade mínima para senador é de 35 anos.'},
                {'pergunta': 'Qual é a idade mínima para concorrer ao cargo de governador?',
                 'opcoes': ['18 anos', '21 anos', '35 anos', '30 anos'],
                 'correta': 3,
                 'explicacao': 'A idade mínima para governador é de 30 anos.'},
                {'pergunta': 'Quem votar em trânsito fora do seu estado poderá votar em qual cargo?',
                 'opcoes': ['Governador', 'Senador', 'Presidente da República', 'Deputado Federal'],
                 'correta': 2,
                 'explicacao': 'Fora da unidade da Federação do domicílio eleitoral, o voto em trânsito é '
                               'apenas para presidente.'},
                {'pergunta': 'No voto em trânsito dentro do próprio estado, em quais cargos é possível '
                             'votar?',
                 'opcoes': ['Somente presidente',
                            'Presidente e governador',
                            'Somente cargos legislativos',
                            'Presidente, governador, senador e deputados'],
                 'correta': 3,
                 'explicacao': 'Dentro do mesmo estado, o eleitor em trânsito pode votar nos cargos das '
                               'eleições gerais.'}],
  'fechamento': 'Quantas dessas regras você já conhecia? Comenta seu placar!'},
 {'id': 'casal_01',
  'layout': 2,
  'tema': 'CASAL FLERTANDO: COMIDA',
  'hashtag': '#CasalFlertando',
  'gancho': 'Você sabe flertar usando os gostos do seu par?',
  'perguntas': [{'pergunta': 'Seu par ama pizza. Qual frase combina mais com a trend?',
                 'opcoes': ['Você é meu pedaço favorito',
                            'Cadê a conta de luz?',
                            'Hoje não tem conversa',
                            'Vou dormir cedo'],
                 'correta': 0,
                 'explicacao': 'A graça da trend é transformar um gosto conhecido do casal em um flerte '
                               'divertido.'},
                {'pergunta': 'Seu par ama café. Qual flerte entra melhor no clima?',
                 'opcoes': ['Seu café esfriou',
                            'Você é meu café favorito',
                            'Compra açúcar',
                            'A caneca está na pia'],
                 'correta': 1,
                 'explicacao': 'A resposta usa o gosto por café como parte da cantada.'},
                {'pergunta': 'Seu par não vive sem chocolate. Qual resposta é mais divertida?',
                 'opcoes': ['Guarda pra amanhã',
                            'Chocolate acabou',
                            'Você é mais doce que meu chocolate',
                            'Não gosto de sobremesa'],
                 'correta': 2,
                 'explicacao': 'A frase transforma o gosto do par em elogio e mantém o tom de flerte.'},
                {'pergunta': 'Seu par ama hambúrguer. Qual convite combina mais?',
                 'opcoes': ['Vamos falar de trabalho',
                            'Vamos arrumar o quarto',
                            'Vamos estudar',
                            'Trouxe seu hambúrguer favorito e minha companhia'],
                 'correta': 3,
                 'explicacao': 'O convite usa um gosto pessoal do par e deixa a interação mais leve.'},
                {'pergunta': 'Qual elemento deixa esse tipo de vídeo mais natural?',
                 'opcoes': ['Reação espontânea', 'Tela parada', 'Texto sem contexto', 'Nenhuma interação'],
                 'correta': 0,
                 'explicacao': 'A reação espontânea ajuda a trend a parecer uma conversa real do casal.'}],
  'fechamento': 'Qual dessas cantadas você usaria? Marca seu par!'},
 {'id': 'casal_02',
  'layout': 2,
  'tema': 'CASAL FLERTANDO: HOBBIES',
  'hashtag': '#CasalFlertando',
  'gancho': 'Qual flerte combina com o hobby do seu par?',
  'perguntas': [{'pergunta': 'Seu par ama videogame. Qual frase entra melhor na trend?',
                 'opcoes': ['Desliga tudo agora',
                            'Você é meu player número um',
                            'A internet acabou',
                            'Vou guardar o controle'],
                 'correta': 1,
                 'explicacao': 'A frase usa o universo do videogame para criar um flerte simples.'},
                {'pergunta': 'Seu par ama academia. Qual cantada combina mais?',
                 'opcoes': ['Hoje eu sou seu cardio',
                            'Faltou lavar a roupa',
                            'Não quero treinar',
                            'Cadê minha garrafa?'],
                 'correta': 0,
                 'explicacao': 'A brincadeira usa um elemento do treino e mantém o tom romântico.'},
                {'pergunta': 'Seu par ama livros. Qual frase combina melhor?',
                 'opcoes': ['Fecha esse livro',
                            'A estante está cheia',
                            'Você é meu capítulo favorito',
                            'Não gosto de ler'],
                 'correta': 2,
                 'explicacao': 'A cantada transforma o hobby da leitura em elogio.'},
                {'pergunta': 'Seu par ama corrida. Qual resposta fica mais na vibe?',
                 'opcoes': ['Vai sozinho', 'Hoje não', 'Esqueci o tênis', 'Eu correria até você'],
                 'correta': 3,
                 'explicacao': 'A frase aproveita o hobby da corrida e vira uma cantada direta.'},
                {'pergunta': 'Na trend, o que deve aparecer primeiro para dar contexto?',
                 'opcoes': ['O gosto do seu par',
                            'Uma propaganda aleatória',
                            'Um assunto sem relação',
                            'Uma tela preta'],
                 'correta': 0,
                 'explicacao': 'Mostrar ou citar o gosto do par ajuda o público a entender a brincadeira.'}],
  'fechamento': 'Seu par passaria nesse teste de flerte?'},
 {'id': 'casal_03',
  'layout': 2,
  'tema': 'CASAL FLERTANDO: ROTINA',
  'hashtag': '#CasalFlertando',
  'gancho': 'Até na rotina dá pra flertar. Qual frase vence?',
  'perguntas': [{'pergunta': 'Seu par ama dormir. Qual flerte combina mais?',
                 'opcoes': ['Levanta agora',
                            'Seu travesseiro sente ciúme de mim',
                            'Arruma a cama',
                            'O despertador tocou'],
                 'correta': 1,
                 'explicacao': 'A frase usa uma situação cotidiana para criar humor e flerte.'},
                {'pergunta': 'Seu par ama cachorro. Qual cantada entra melhor na trend?',
                 'opcoes': ['Você é meu humano favorito também',
                            'O cachorro latiu',
                            'Compra ração',
                            'Vamos passear depois'],
                 'correta': 0,
                 'explicacao': 'A brincadeira usa o carinho pelo pet como parte do flerte.'},
                {'pergunta': 'Seu par ama música. Qual frase combina mais?',
                 'opcoes': ['Baixa o volume',
                            'Troca a playlist',
                            'Você é minha música favorita',
                            'Cadê o fone?'],
                 'correta': 2,
                 'explicacao': 'A frase liga diretamente o gosto musical ao elogio.'},
                {'pergunta': 'Seu par ama viajar. Qual convite fica melhor?',
                 'opcoes': ['Fica em casa',
                            'Vamos pagar boletos',
                            'Arruma a mala sozinho',
                            'Meu destino favorito é com você'],
                 'correta': 3,
                 'explicacao': 'A frase usa viagem como metáfora de parceria.'},
                {'pergunta': 'Qual final combina melhor com esse formato?',
                 'opcoes': ['Qual seria o flerte do seu casal?',
                            'Não comenta',
                            'Fim sem reação',
                            'Muda de assunto'],
                 'correta': 0,
                 'explicacao': 'Uma pergunta final incentiva o público a participar da trend.'}],
  'fechamento': 'Qual seria o flerte perfeito para o seu casal?'},
 {'id': 'rockinrio_01',
  'layout': 3,
  'tema': 'ROCK IN RIO: VIBE DE FESTIVAL',
  'hashtag': '#rockinrio',
  'gancho': 'Qual é a sua vibe de festival?',
  'perguntas': [{'pergunta': 'Qual item costuma ser prioridade para aguentar horas de festival?',
                 'opcoes': ['Tênis confortável', 'Salto muito fino', 'Sapato apertado', 'Chinelo solto'],
                 'correta': 0,
                 'explicacao': 'Conforto nos pés costuma ser uma escolha prática para longos períodos em pé '
                               'e caminhando.'},
                {'pergunta': 'Para acompanhar horários de shows, o que ajuda mais?',
                 'opcoes': ['Ignorar a programação',
                            'Consultar a programação oficial',
                            'Escolher no acaso',
                            'Perguntar só no fim'],
                 'correta': 1,
                 'explicacao': 'Consultar a programação oficial ajuda a organizar os shows que você quer '
                               'assistir.'},
                {'pergunta': 'Qual conteúdo combina melhor com a hashtag de festival?',
                 'opcoes': ['Conta de matemática',
                            'Receita sem relação',
                            'Preparação, shows e curiosidades',
                            'Manual de impressora'],
                 'correta': 2,
                 'explicacao': 'Preparação, shows, artistas e experiências têm relação direta com a vibe do '
                               'festival.'},
                {'pergunta': 'Se você quer registrar o dia inteiro, qual cuidado é mais útil?',
                 'opcoes': ['Usar bateria até zerar cedo',
                            'Desligar o celular',
                            'Não levar nada',
                            'Planejar a bateria do celular'],
                 'correta': 3,
                 'explicacao': 'Planejar o uso de bateria ajuda a registrar mais momentos ao longo do '
                               'evento.'},
                {'pergunta': 'Qual fechamento combina melhor com um vídeo de festival?',
                 'opcoes': ['Qual show você mais quer ver?',
                            'Não responde',
                            'Fim sem contexto',
                            'Assunto aleatório'],
                 'correta': 0,
                 'explicacao': 'Perguntar sobre o show mais esperado aproxima o público do tema.'}],
  'fechamento': 'Qual é a sua vibe no Rock in Rio?'},
 {'id': 'rockinrio_02',
  'layout': 3,
  'tema': 'ROCK IN RIO: SOBREVIVÊNCIA NO FESTIVAL',
  'hashtag': '#rockinrio',
  'gancho': 'Você sobreviveria a um dia inteiro de festival?',
  'perguntas': [{'pergunta': 'Antes de sair para um festival, o que vale conferir primeiro?',
                 'opcoes': ['Somente a câmera',
                            'Ingressos e orientações oficiais',
                            'A cor da parede',
                            'O controle remoto'],
                 'correta': 1,
                 'explicacao': 'Conferir ingresso, acesso e orientações oficiais evita imprevistos na '
                               'entrada.'},
                {'pergunta': 'Qual atitude ajuda a aproveitar melhor vários shows?',
                 'opcoes': ['Planejar os horários principais',
                            'Chegar sem olhar nada',
                            'Escolher tudo depois',
                            'Ignorar deslocamentos'],
                 'correta': 0,
                 'explicacao': 'Um planejamento simples ajuda a conciliar palcos e deslocamentos.'},
                {'pergunta': 'Qual item faz mais sentido verificar nas regras oficiais antes de levar?',
                 'opcoes': ['Quadro de parede', 'Abajur', 'Objetos permitidos e proibidos', 'Panela'],
                 'correta': 2,
                 'explicacao': 'As regras do evento informam quais itens podem ou não entrar no local.'},
                {'pergunta': 'Em um festival grande, qual estratégia ajuda na hora de encontrar amigos?',
                 'opcoes': ['Nunca combinar nada',
                            'Desligar o celular',
                            'Cada um ir para um lado',
                            'Combinar um ponto de encontro'],
                 'correta': 3,
                 'explicacao': 'Um ponto de encontro combinado facilita a reunião do grupo em locais '
                               'movimentados.'},
                {'pergunta': 'Qual tipo de vídeo combina com a preparação para o festival?',
                 'opcoes': ['Arrume-se comigo',
                            'Manual de planilha',
                            'Aula de hidráulica',
                            'Tutorial sem relação'],
                 'correta': 0,
                 'explicacao': 'Conteúdo de preparação e look se conecta diretamente ao clima de festival.'}],
  'fechamento': 'Você passaria um dia inteiro no festival sem perrengue?'},
 {'id': 'rockinrio_03',
  'layout': 3,
  'tema': 'ROCK IN RIO: VOCÊ É QUAL TIPO?',
  'hashtag': '#rockinrio',
  'gancho': 'No festival, qual dessas situações tem mais a sua cara?',
  'perguntas': [{'pergunta': 'Quem quer ficar perto do palco costuma precisar fazer o quê?',
                 'opcoes': ['Chegar só depois do show',
                            'Se organizar com antecedência',
                            'Esperar todo mundo sair',
                            'Ir embora cedo'],
                 'correta': 1,
                 'explicacao': 'Se organizar com antecedência ajuda quem pretende buscar uma posição '
                               'específica.'},
                {'pergunta': 'Qual registro mostra melhor a experiência completa do dia?',
                 'opcoes': ['Só uma tela preta',
                            'Apenas o ingresso',
                            'Preparação, chegada e momentos dos shows',
                            'Nenhuma imagem'],
                 'correta': 2,
                 'explicacao': 'Uma sequência com preparação, chegada e shows conta melhor a experiência.'},
                {'pergunta': 'Qual pergunta gera mais interação em conteúdo de festival?',
                 'opcoes': ['Qual artista você mais quer ver?',
                            'Qual sua senha?',
                            'Qual sua conta bancária?',
                            'Qual sua placa?'],
                 'correta': 0,
                 'explicacao': 'Perguntar sobre artistas e shows mantém a conversa dentro do tema do '
                               'festival.'},
                {'pergunta': 'Se chover, qual atitude faz mais sentido?',
                 'opcoes': ['Ignorar qualquer orientação',
                            'Levar equipamento proibido',
                            'Sair correndo sem rumo',
                            'Seguir as orientações do evento e se preparar'],
                 'correta': 3,
                 'explicacao': 'Planejamento e atenção às orientações do evento ajudam em mudanças de '
                               'tempo.'},
                {'pergunta': 'Qual estética combina mais com um vídeo de festival?',
                 'opcoes': ['Luzes, palco e energia',
                            'Documento em preto e branco',
                            'Tela de calculadora',
                            'Papel em branco'],
                 'correta': 0,
                 'explicacao': 'Luzes e elementos de palco reforçam imediatamente a atmosfera de festival.'}],
  'fechamento': 'Você é do time grade, passeio ou vlog?'},
 {'id': 'cinema_01',
  'layout': 4,
  'tema': 'SEMANA DO CINEMA: ROLÊ PERFEITO',
  'hashtag': '#SemanaDoCinema',
  'gancho': 'Você sabe montar o rolê perfeito de cinema?',
  'perguntas': [{'pergunta': 'O que normalmente é exibido antes do filme principal para divulgar outros '
                             'lançamentos?',
                 'opcoes': ['Trailer', 'Créditos finais', 'Legenda', 'Intervalo técnico'],
                 'correta': 0,
                 'explicacao': 'O trailer apresenta cenas e informações promocionais de outros filmes.'},
                {'pergunta': 'Qual lugar costuma oferecer a melhor visão para quem prefere ficar '
                             'centralizado?',
                 'opcoes': ['Atrás da tela', 'Região central da sala', 'Corredor externo', 'Hall do cinema'],
                 'correta': 1,
                 'explicacao': 'A região central costuma oferecer um ângulo mais equilibrado para a tela.'},
                {'pergunta': 'Qual item é tradicionalmente associado à experiência de cinema?',
                 'opcoes': ['Feijão', 'Macarrão', 'Pipoca', 'Sopa'],
                 'correta': 2,
                 'explicacao': 'Pipoca é um dos alimentos mais associados culturalmente às sessões de '
                               'cinema.'},
                {'pergunta': 'Qual atitude demonstra respeito durante a sessão?',
                 'opcoes': ['Conversar alto', 'Usar flash', 'Atender ligação', 'Manter o celular silencioso'],
                 'correta': 3,
                 'explicacao': 'Manter o celular silencioso evita atrapalhar outras pessoas na sala.'},
                {'pergunta': 'Qual chamada combina melhor com a hashtag?',
                 'opcoes': ['Qual filme você escolheria?',
                            'Qual sua senha?',
                            'Qual seu boleto?',
                            'Qual seu roteador?'],
                 'correta': 0,
                 'explicacao': 'Perguntar sobre filmes mantém a interação ligada ao tema cinema.'}],
  'fechamento': 'Qual filme merece sua sessão na telona?'},
 {'id': 'cinema_02',
  'layout': 4,
  'tema': 'SEMANA DO CINEMA: GÊNEROS',
  'hashtag': '#SemanaDoCinema',
  'gancho': 'Você reconhece o gênero do filme pela descrição?',
  'perguntas': [{'pergunta': 'Um filme feito principalmente para provocar medo pertence a qual gênero?',
                 'opcoes': ['Comédia', 'Terror', 'Musical', 'Documentário'],
                 'correta': 1,
                 'explicacao': 'Terror é o gênero voltado principalmente a criar medo, tensão ou suspense '
                               'intenso.'},
                {'pergunta': 'Qual gênero normalmente usa humor como elemento principal?',
                 'opcoes': ['Comédia', 'Ficção científica', 'Drama', 'Suspense'],
                 'correta': 0,
                 'explicacao': 'Comédia usa situações e recursos humorísticos como característica central.'},
                {'pergunta': 'Histórias com tecnologia futurista e exploração espacial aparecem com '
                             'frequência em qual gênero?',
                 'opcoes': ['Faroeste', 'Romance', 'Ficção científica', 'Biografia'],
                 'correta': 2,
                 'explicacao': 'Ficção científica explora com frequência tecnologia, futuro e espaço.'},
                {'pergunta': 'Qual gênero costuma ter números de canto e dança integrados à narrativa?',
                 'opcoes': ['Suspense', 'Ação', 'Terror', 'Musical'],
                 'correta': 3,
                 'explicacao': 'Musicais integram canções e performances à construção da história.'},
                {'pergunta': 'Um filme que registra fatos e pessoas reais é normalmente chamado de quê?',
                 'opcoes': ['Documentário', 'Fantasia', 'Animação', 'Aventura'],
                 'correta': 0,
                 'explicacao': 'Documentários trabalham com registros e temas do mundo real.'}],
  'fechamento': 'Qual gênero é o seu favorito na telona?'},
 {'id': 'cinema_03',
  'layout': 4,
  'tema': 'SEMANA DO CINEMA: BASTIDORES',
  'hashtag': '#SemanaDoCinema',
  'gancho': 'Você conhece essas palavras do mundo do cinema?',
  'perguntas': [{'pergunta': 'Quem é responsável por conduzir artisticamente a filmagem de uma obra?',
                 'opcoes': ['Bilheteiro', 'Diretor', 'Público', 'Projencionista'],
                 'correta': 1,
                 'explicacao': 'O diretor coordena a visão artística da produção audiovisual.'},
                {'pergunta': 'Como se chama o texto que organiza cenas, falas e ações de um filme?',
                 'opcoes': ['Roteiro', 'Ingresso', 'Cartaz', 'Legenda'],
                 'correta': 0,
                 'explicacao': 'O roteiro estrutura cenas, ações, diálogos e outros elementos narrativos.'},
                {'pergunta': 'Qual profissional trabalha diretamente na interpretação de personagens?',
                 'opcoes': ['Montador', 'Operador de caixa', 'Ator ou atriz', 'Distribuidor'],
                 'correta': 2,
                 'explicacao': 'Atores e atrizes interpretam personagens diante das câmeras.'},
                {'pergunta': 'O que geralmente aparece ao final do filme listando a equipe da produção?',
                 'opcoes': ['Trailer', 'Pôster', 'Sinopse', 'Créditos'],
                 'correta': 3,
                 'explicacao': 'Os créditos identificam profissionais e empresas participantes da produção.'},
                {'pergunta': 'Como se chama o resumo curto da história de um filme?',
                 'opcoes': ['Sinopse', 'Bilheteria', 'Dublagem', 'Sessão'],
                 'correta': 0,
                 'explicacao': 'A sinopse apresenta de forma resumida a premissa da obra.'}],
  'fechamento': 'Quantos termos de cinema você acertou?'},
 {'id': 'peao_01',
  'layout': 5,
  'tema': 'NOSSA UM PEÃO DESSE: LOOK COUNTRY',
  'hashtag': '#NossaUmPeãoDesse',
  'gancho': 'Você reconhece uma vibe country de longe?',
  'perguntas': [{'pergunta': 'Qual calçado é fortemente associado ao visual country?',
                 'opcoes': ['Bota', 'Nadadeira', 'Pantufa', 'Sapatilha de balé'],
                 'correta': 0,
                 'explicacao': 'Botas são um elemento muito associado à estética country e sertaneja.'},
                {'pergunta': 'Qual acessório combina mais com a estética de peão?',
                 'opcoes': ['Touca de natação', 'Chapéu', 'Coroa medieval', 'Capacete de ciclismo'],
                 'correta': 1,
                 'explicacao': 'O chapéu é um dos símbolos mais reconhecíveis da estética country.'},
                {'pergunta': 'Qual peça aparece com frequência em looks country?',
                 'opcoes': ['Avental', 'Quimono', 'Camisa xadrez', 'Jaleco'],
                 'correta': 2,
                 'explicacao': 'Camisas xadrez são frequentemente usadas em composições de estilo country.'},
                {'pergunta': 'Qual combinação combina mais com uma trend de peão?',
                 'opcoes': ['Terno e nadadeira',
                            'Pijama e chinelo',
                            'Jaleco e touca',
                            'Jeans, bota e chapéu'],
                 'correta': 3,
                 'explicacao': 'Jeans, bota e chapéu formam uma combinação visual imediatamente associada ao '
                               'country.'},
                {'pergunta': 'Qual cenário combina mais com essa estética?',
                 'opcoes': ['Rodeio ou festa country',
                            'Laboratório',
                            'Piscina olímpica',
                            'Escritório corporativo'],
                 'correta': 0,
                 'explicacao': 'Rodeios e festas country reforçam a ambientação típica desse estilo.'}],
  'fechamento': 'Qual item não pode faltar no seu peão ideal?'},
 {'id': 'peao_02',
  'layout': 5,
  'tema': 'NOSSA UM PEÃO DESSE: VIBE SERTANEJA',
  'hashtag': '#NossaUmPeãoDesse',
  'gancho': 'Qual opção combina mais com uma vibe sertaneja?',
  'perguntas': [{'pergunta': 'Qual instrumento é muito associado à música sertaneja brasileira?',
                 'opcoes': ['Harpa', 'Viola caipira', 'Oboé', 'Tímpano'],
                 'correta': 1,
                 'explicacao': 'A viola caipira tem forte ligação histórica com a música caipira e '
                               'sertaneja.'},
                {'pergunta': 'Qual dança aparece com frequência em festas de clima country?',
                 'opcoes': ['Dança de salão country', 'Balé clássico', 'Dança aquática', 'Patinação'],
                 'correta': 0,
                 'explicacao': 'Dançar em pares e estilos country combina com esse ambiente festivo.'},
                {'pergunta': 'Qual peça combina melhor com jeans em um look country?',
                 'opcoes': ['Pé de pato', 'Avental', 'Cinto com fivela', 'Máscara de mergulho'],
                 'correta': 2,
                 'explicacao': 'Cintos e fivelas marcantes são comuns em composições country.'},
                {'pergunta': 'Qual ambiente combina mais com uma playlist sertaneja?',
                 'opcoes': ['Biblioteca silenciosa', 'Sala de cirurgia', 'Laboratório', 'Festa country'],
                 'correta': 3,
                 'explicacao': 'Uma festa country combina naturalmente com repertório sertanejo.'},
                {'pergunta': 'Qual chamada final funciona melhor para essa trend?',
                 'opcoes': ['Qual seria o seu peão ideal?',
                            'Qual sua senha?',
                            'Qual seu imposto?',
                            'Qual seu IP?'],
                 'correta': 0,
                 'explicacao': 'A pergunta convida o público a entrar na brincadeira da trend.'}],
  'fechamento': 'Qual é a vibe do seu peão ideal?'},
 {'id': 'peao_03',
  'layout': 5,
  'tema': 'NOSSA UM PEÃO DESSE: FLERTE COUNTRY',
  'hashtag': '#NossaUmPeãoDesse',
  'gancho': 'Qual cantada merece o chapéu de ouro?',
  'perguntas': [{'pergunta': 'Qual frase combina mais com um flerte country?',
                 'opcoes': ['Você roubou meu coração antes do rodeio começar',
                            'Cadê o relatório?',
                            'A impressora travou',
                            'Desliga o computador'],
                 'correta': 0,
                 'explicacao': 'A frase usa o universo do rodeio como parte da cantada.'},
                {'pergunta': 'Qual convite entra melhor na brincadeira?',
                 'opcoes': ['Vamos organizar a planilha',
                            'Aceita uma dança comigo?',
                            'Vamos limpar a garagem',
                            'Quer revisar um contrato?'],
                 'correta': 1,
                 'explicacao': 'O convite para dançar combina com o clima romântico e country da trend.'},
                {'pergunta': 'Qual elogio combina mais com o tema?',
                 'opcoes': ['Sua impressora é rápida',
                            'Seu Wi-Fi é bom',
                            'Esse chapéu ficou perfeito em você',
                            'Sua conta chegou'],
                 'correta': 2,
                 'explicacao': 'O elogio usa um elemento visual típico da estética country.'},
                {'pergunta': 'Qual final fica mais divertido?',
                 'opcoes': ['Fim sem olhar para a câmera',
                            'Tela preta',
                            'Mudar de assunto',
                            'E aí, você cairia nesse flerte?'],
                 'correta': 3,
                 'explicacao': 'Uma pergunta final transforma a cantada em convite para interação.'},
                {'pergunta': 'Qual reação combina mais com o vídeo?',
                 'opcoes': ['Sorriso e surpresa', 'Nenhuma reação', 'Tela vazia', 'Silêncio sem contexto'],
                 'correta': 0,
                 'explicacao': 'Uma reação visível ajuda o público a entender a graça da cena.'}],
  'fechamento': 'Você cairia nesse flerte country?'},
 {'id': 'morango_01',
  'layout': 6,
  'tema': 'MORANGO CRAVEJADO: VALE A FAMA?',
  'hashtag': '#MorangoCravejado',
  'gancho': 'Você provaria essa trend de morango?',
  'perguntas': [{'pergunta': 'Qual fruta é a estrela dessa trend?',
                 'opcoes': ['Morango', 'Banana', 'Abacaxi', 'Melancia'],
                 'correta': 0,
                 'explicacao': 'O morango é o elemento central da trend.'},
                {'pergunta': 'Qual característica visual costuma chamar atenção em doces virais?',
                 'opcoes': ['Ausência de cor',
                            'Cobertura e acabamento marcantes',
                            'Embalagem vazia',
                            'Nenhum detalhe'],
                 'correta': 1,
                 'explicacao': 'Acabamento visual e cobertura ajudam a criar o efeito chamativo típico de '
                               'doces virais.'},
                {'pergunta': 'Antes de preparar frutas, qual cuidado básico é importante?',
                 'opcoes': ['Pintar a fruta',
                            'Guardar no sol',
                            'Higienizar adequadamente',
                            'Usar embalagem suja'],
                 'correta': 2,
                 'explicacao': 'A higienização adequada é um cuidado básico no preparo de frutas.'},
                {'pergunta': 'Qual tipo de vídeo combina melhor com uma trend de doce?',
                 'opcoes': ['Manual de impressora',
                            'Planilha financeira',
                            'Tutorial elétrico',
                            'Preparo, corte e reação'],
                 'correta': 3,
                 'explicacao': 'Mostrar preparo, resultado e reação cria uma sequência completa para '
                               'conteúdo de comida.'},
                {'pergunta': 'Qual pergunta final gera mais comentários?',
                 'opcoes': ['Você provaria?', 'Qual seu CPF?', 'Qual seu roteador?', 'Qual sua senha?'],
                 'correta': 0,
                 'explicacao': 'Perguntar se o público provaria convida a uma resposta rápida e relacionada '
                               'ao vídeo.'}],
  'fechamento': 'Você provaria ou passaria essa trend?'},
 {'id': 'morango_02',
  'layout': 6,
  'tema': 'MORANGO CRAVEJADO: COMBINAÇÕES',
  'hashtag': '#MorangoCravejado',
  'gancho': 'Qual combinação de morango ganha seu voto?',
  'perguntas': [{'pergunta': 'Qual ingrediente combina classicamente com morango em sobremesas?',
                 'opcoes': ['Molho de soja', 'Chocolate', 'Mostarda', 'Vinagre'],
                 'correta': 1,
                 'explicacao': 'Morango com chocolate é uma combinação clássica em sobremesas.'},
                {'pergunta': 'Qual textura cria contraste com uma fruta macia?',
                 'opcoes': ['Crocante', 'Líquida apenas', 'Gasosa', 'Sem textura'],
                 'correta': 0,
                 'explicacao': 'Uma camada crocante cria contraste com a textura macia da fruta.'},
                {'pergunta': 'Qual detalhe ajuda a valorizar o visual de uma sobremesa?',
                 'opcoes': ['Embalagem amassada', 'Prato sujo', 'Finalização caprichada', 'Luz apagada'],
                 'correta': 2,
                 'explicacao': 'Uma finalização caprichada ajuda a destacar cores, camadas e textura.'},
                {'pergunta': 'Qual enquadramento ajuda a mostrar melhor a cobertura?',
                 'opcoes': ['Câmera apontada para o teto',
                            'Imagem muito distante',
                            'Tela preta',
                            'Close no doce'],
                 'correta': 3,
                 'explicacao': 'O close mostra melhor os detalhes da cobertura e do acabamento.'},
                {'pergunta': 'Qual conteúdo pode aumentar a curiosidade antes da revelação?',
                 'opcoes': ['Mostrar o processo em etapas',
                            'Entregar o final antes de começar',
                            'Mudar de assunto',
                            'Ocultar o doce inteiro'],
                 'correta': 0,
                 'explicacao': 'Mostrar o processo em etapas cria expectativa até o resultado final.'}],
  'fechamento': 'Qual combinação você escolheria para seu morango?'},
 {'id': 'morango_03',
  'layout': 6,
  'tema': 'MORANGO CRAVEJADO: TESTE DA TREND',
  'hashtag': '#MorangoCravejado',
  'gancho': 'Será que essa trend merece o hype?',
  'perguntas': [{'pergunta': 'Qual é uma boa forma de testar uma trend de comida em vídeo?',
                 'opcoes': ['Não mostrar o resultado',
                            'Mostrar preparo e provar no final',
                            'Usar só texto',
                            'Falar de outro assunto'],
                 'correta': 1,
                 'explicacao': 'Mostrar preparo e reação final permite que o público acompanhe o teste '
                               'completo.'},
                {'pergunta': 'Qual abertura desperta mais curiosidade?',
                 'opcoes': ['Será que vale a fama?',
                            'Hoje não tem vídeo',
                            'Nada para mostrar',
                            'Ignore isso'],
                 'correta': 0,
                 'explicacao': 'Uma pergunta sobre a fama da trend cria expectativa pelo resultado.'},
                {'pergunta': 'O que deixa a reação mais convincente?',
                 'opcoes': ['Não provar',
                            'Cortar antes da reação',
                            'Mostrar a reação logo após provar',
                            'Trocar de tema'],
                 'correta': 2,
                 'explicacao': 'Mostrar a reação imediatamente após provar conecta o resultado ao teste.'},
                {'pergunta': 'Qual cena valoriza melhor o interior da sobremesa?',
                 'opcoes': ['Parede vazia',
                            'Embalagem fechada',
                            'Tela inicial',
                            'Corte mostrando as camadas'],
                 'correta': 3,
                 'explicacao': 'O corte revela as camadas e ajuda o público a entender a textura.'},
                {'pergunta': 'Qual CTA combina mais com o final?',
                 'opcoes': ['Você provaria essa versão?',
                            'Não comenta',
                            'Muda de assunto',
                            'Fecha o vídeo sem pergunta'],
                 'correta': 0,
                 'explicacao': 'Perguntar se a pessoa provaria mantém a conversa ligada ao resultado.'}],
  'fechamento': 'Vale a fama ou é só hype? Comenta!'}]
